language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: LARAVEL='7.*' TESTBENCH='5.*'
    - php: 7.3
      env: LARAVEL='7.*' TESTBENCH='5.*'
    - php: 7.4
      env: LARAVEL='7.*' TESTBENCH='5.*'

before_install:
  - travis_retry composer self-update
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer require --no-update --no-interaction "illuminate/support:${LARAVEL}" "illuminate/console:${LARAVEL}" "orchestra/testbench:${TESTBENCH}"

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update --no-interaction --no-plugins --no-suggest --prefer-source ${COMPOSER_FLAGS}

script:
  - composer test

notifications:
  email: false
